server:
  port: 8888

spring:
  profiles:
    include: oauth, real-db, real, aws

  h2:
    console:
      enabled=true:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 2s

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  mail:
    host=smtp: gmail.com
    port: 587
    username: feelsocoold@gmail.com
    password: pofnjdyfjpdngtvo
    smtp:
      starttls:
        enable: true
      auth: true

  servlet:
    multipart:
      max-file-size: 10MB

cloud:
  aws:
    s3:
      bucket: manalive-attach
    region:
      static: ap-northeast-2
    stack:
      auto: false



